// Swagger definition.
var swaggerDefinition = {
  info: {
    title: 'Barbos API',
    version: '1.0.0',
    description: 'RESTful API docs generated by Swagger',
  },
  host: 'localhost:3000',
  basePath: '/'
};

// Options for the swagger docs.
var options = {
  // Import swaggerDefinitions.
  swaggerDefinition: swaggerDefinition,
  // Path to the API docs
  apis: ['./src/*/index.js'],
};

exports.swagger = options;
